import { GENERIC_PATHS } from './util.routes';

export const PROPOSAL_PATHS = {
  BASE: 'proposals',
  VOTE: 'vote',
  MANAGE: 'manage',
  CREATE: 'create',
};

export const PROPOSAL_HREFS = {
  BASE: `/${PROPOSAL_PATHS.BASE}`,
  VOTE_ALL: `${PROPOSAL_PATHS.BASE}/${PROPOSAL_PATHS.VOTE}/${GENERIC_PATHS.ALL}`,
  VOTE_ONE: `${PROPOSAL_PATHS.BASE}/${PROPOSAL_PATHS.VOTE}/${GENERIC_PATHS.ONE}`,
  MANAGE_ALL: `${PROPOSAL_PATHS.BASE}/${PROPOSAL_PATHS.MANAGE}/${GENERIC_PATHS.ALL}`,
  MANAGE_ONE: `${PROPOSAL_PATHS.BASE}/${PROPOSAL_PATHS.MANAGE}/${GENERIC_PATHS.ONE}`,
  CREATE: `${PROPOSAL_PATHS.BASE}/${PROPOSAL_PATHS.CREATE}`,
} as const;
