export const USER_PROFILE_PATHS = {
  BASE: 'profile',
  PROFILE: '',
  HISTORY: 'history',
};

export const USER_PROFILE_HREFS = {
  BASE: `/${USER_PROFILE_PATHS.BASE}`,
  HISTORY: `/${USER_PROFILE_PATHS.BASE}/${USER_PROFILE_PATHS.HISTORY}`,
};

export const USER_TEMPLATES_PATHS = {
  BASE: 'templates',
  MANAGER: 'manager',
};

export const USER_TEMPLATES_HREFS = {
  BASE: `${USER_PROFILE_HREFS.BASE}/${USER_TEMPLATES_PATHS.BASE}`,
  MANAGER: `${USER_PROFILE_HREFS.BASE}/${USER_TEMPLATES_PATHS.BASE}/${USER_TEMPLATES_PATHS.MANAGER}`,
};
